common: &common
  access_key_id: 'AKIAJ3CCTJY54TJGQKRQ'
  secret_access_key: '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'

development:
  <<: *common
  bucket: dandoo.dev

production:
  <<: *common
  bucket: dandoo